"""Calibrate the live-E2E synthetic microseismic contract (two-pass golden).

Writes the fixture config YAML for the 22-DAT synthetic bundle generated by
``microseismicBundle.ts``, then runs the real derivation twice — first with
placeholder golden pins to harvest the actual hashes, then with the final
config to prove the whole gate chain passes. This mirrors
``tests/test_microseismic_api.py::build_synthetic_bundle``: the fixture
config's expected counts/hashes are generated from the fixture itself and
never embed private bytes (no 2,006/1,925 evidence anywhere).

Usage:
    python calibrate_microseismic_config.py <config_path> <data_dir> <work_dir>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

from geomodeling.microseismic.config import load_microseismic_config
from geomodeling.microseismic.service import derive_from_directory

RULE_VERSION = "microseismic_e2e_live_synthetic_v0.5"

# 文件名清单与 config/microseismic.yaml 的 expected 清单一一对应（公开合同）。
BUNDLE_LINES: list[tuple[str, list[tuple[str, str]]]] = [
    ("L1", [(f"W{i}", f"W{i}.dat") for i in range(1, 10)]),
    ("L2", [(f"W{i}", f"WD{i}-Vx.dat") for i in range(12, 21)]),
    ("L3", [(f"W{i}", f"WD{i}-Vx.dat") for i in range(24, 28)]),
]

# 测线间距与局部坐标沿用已入库的公开工程值（config/microseismic.yaml 同款）。
INTERVALS_M = {
    "L1": [
        {"from": "W1", "to": "W2", "distance_m": 150},
        {"from": "W2", "to": "W3", "distance_m": 100},
        {"from": "W3", "to": "W4", "distance_m": 100},
        {"from": "W4", "to": "W5", "distance_m": 50},
        {"from": "W5", "to": "W6", "distance_m": 50},
        {"from": "W6", "to": "W7", "distance_m": 150},
        {"from": "W7", "to": "W8", "distance_m": 250},
        {"from": "W8", "to": "W9", "distance_m": 300},
    ],
    "L2": [
        {"from": "W12", "to": "W13", "distance_m": 275},
        {"from": "W13", "to": "W14", "distance_m": 275},
        {"from": "W14", "to": "W15", "distance_m": 250},
        {"from": "W15", "to": "W16", "distance_m": 195},
        {"from": "W16", "to": "W17", "distance_m": 110},
        {"from": "W17", "to": "W18", "distance_m": 600},
        {"from": "W18", "to": "W19", "distance_m": 300},
        {"from": "W19", "to": "W20", "distance_m": 300},
    ],
    "L3": [
        {"from": "W24", "to": "W25", "distance_m": 800},
        {"from": "W25", "to": "W26", "distance_m": 320},
        {"from": "W26", "to": "W27", "distance_m": 335},
    ],
}

LOCAL_COORDINATES = [
    {"point_id": "W1", "x_local_m": 400, "y_local_m": 220},
    {"point_id": "W2", "x_local_m": 250, "y_local_m": 220},
    {"point_id": "W3", "x_local_m": 150, "y_local_m": 220},
    {"point_id": "W4", "x_local_m": 50, "y_local_m": 220},
    {"point_id": "W5", "x_local_m": 0, "y_local_m": 220},
    {"point_id": "W6", "x_local_m": -50, "y_local_m": 220},
    {"point_id": "W7", "x_local_m": -200, "y_local_m": 220},
    {"point_id": "W8", "x_local_m": -450, "y_local_m": 220},
    {"point_id": "W9", "x_local_m": -750, "y_local_m": 220},
    {"point_id": "W12", "x_local_m": 0, "y_local_m": -995},
    {"point_id": "W13", "x_local_m": 0, "y_local_m": -720},
    {"point_id": "W14", "x_local_m": 0, "y_local_m": -445},
    {"point_id": "W15", "x_local_m": 0, "y_local_m": -195},
    {"point_id": "W16", "x_local_m": 0, "y_local_m": 0},
    {"point_id": "W17", "x_local_m": 0, "y_local_m": 110},
    {"point_id": "W18", "x_local_m": 0, "y_local_m": 710},
    {"point_id": "W19", "x_local_m": 0, "y_local_m": 1010},
    {"point_id": "W20", "x_local_m": 0, "y_local_m": 1310},
    {"point_id": "W24", "x_local_m": 960, "y_local_m": 0},
    {"point_id": "W25", "x_local_m": 160, "y_local_m": 0},
    {"point_id": "W26", "x_local_m": -160, "y_local_m": 0},
    {"point_id": "W27", "x_local_m": -495, "y_local_m": 0},
]


def build_fixture_doc(data_dir: Path, work_dir: Path) -> dict:
    """Fixture contract: 22 files × 2 rows + one W8 QNAN row.

    Counts are the fixture's own (45 source / 44 finite / 1 invalid, tight
    values → zero 3σ rejections, distinct depths per row → 44 unique modeling
    nodes); every file carries exactly one NUL terminator pseudo-line.
    """

    return {
        "project": {"name": "GeoModelingPlatform", "version": "0.5-e2e-live-fixture"},
        "source": {
            "data_dir": data_dir.as_posix(),
            "interval_workbook": "fixture-intervals.xlsx",
            "paper_reference": "fixture-paper.pdf",
            "line_map_image": "fixture-lines.jpg",
            "source_unit": "WL/2(km); Vx km/s",
        },
        "lines": [
            {
                "line_id": line_id,
                "point_start": points[0][0],
                "point_end": points[-1][0],
                "points": [
                    {"point_id": point_id, "source_file": file_name}
                    for point_id, file_name in points
                ],
            }
            for line_id, points in BUNDLE_LINES
        ],
        "intervals_m": INTERVALS_M,
        "excluded_points": [
            {
                "point_id": "W28",
                "line_id": "L3",
                "conflict_interval_m": 350,
                "interval_from": "W27",
                "reason": "e2e-live fixture conflict-only point",
                "issue_code": "L3_W28_SOURCE_CONFLICT",
            }
        ],
        "local_coordinates": LOCAL_COORDINATES,
        "derivation": {
            "rule_version": RULE_VERSION,
            "adapter_version": "0.5.0",
            "depth_multiplier": 1000.0,
            "z_multiplier": -1.0,
            "vx_unit": "km/s",
            "sigma_threshold": 3.0,
            "sigma_ddof": 1,
            "aggregation_method": "arithmetic_mean_exact_xyz",
            "expected_rejected": 0,
            "expected_accepted": 44,
            "expected_conflict_groups": 0,
            "expected_conflict_rows": 0,
            "expected_modeling_nodes": 44,
            "golden": {"accepted_sha256": "0" * 64, "rejected_sha256": "0" * 64},
        },
        "expected": {
            "dat_file_count": 22,
            "nul_terminator_count": 22,
            "line_point_counts": {"L1": 9, "L2": 9, "L3": 4},
            "source_record_counts": {"L1": 19, "L2": 18, "L3": 8},
            "source_record_total": 45,
            "valid_numeric_counts": {"L1": 18, "L2": 18, "L3": 8},
            "valid_numeric_total": 44,
            "invalid_numeric_total": 1,
            "special_nan_token": "1.#QNAN0",
            "special_nan_point": "W8",
            "paper_counts": {"L1": 19, "L2": 18, "L3": 8, "total": 45},
        },
        "cleaning_conflicts": {
            "outlier_count_claim": 80,
            "rate_claim_percent": 3.59,
            "computed_rate_percent": 3.99,
            "method_a": "linear interpolation",
            "method_b": "nearest 5 point IDW",
        },
        "outputs": {"default_dir": work_dir.as_posix()},
    }


def _derive(config_path: Path, data_dir: Path, out_dir: Path):
    config = load_microseismic_config(config_path)
    result, _ = derive_from_directory(config, data_dir, out_dir)
    return result


def main() -> int:
    config_path = Path(sys.argv[1])
    data_dir = Path(sys.argv[2])
    work_dir = Path(sys.argv[3])
    work_dir.mkdir(parents=True, exist_ok=True)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    doc = build_fixture_doc(data_dir, work_dir)
    config_path.write_text(yaml.safe_dump(doc, allow_unicode=True), encoding="utf-8")

    first = _derive(config_path, data_dir, work_dir / "calibration-a")
    if not first.audit.validation.passed:
        raise SystemExit("合成包的审计合同必须在第一遍就通过")
    actual = {check.name: check.actual for check in first.golden.checks}
    doc["derivation"]["golden"] = {
        "accepted_sha256": actual["accepted_sha256"],
        "rejected_sha256": actual["rejected_sha256"],
    }
    config_path.write_text(yaml.safe_dump(doc, allow_unicode=True), encoding="utf-8")

    final = _derive(config_path, data_dir, work_dir / "calibration-b")
    if not final.validation.passed:
        raise SystemExit("标定后的黄金门禁必须整体通过")

    print(
        json.dumps(
            {
                "config": str(config_path),
                "rule_version": RULE_VERSION,
                "golden": doc["derivation"]["golden"],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
